# Generated by Django 4.1 on 2025-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='temporary_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
