# Generated by Django 4.1 on 2025-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
