# Generated by Django 4.1 on 2025-05-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_restaurant_temporary_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='temporary_field',
        ),
    ]
